services:
  db:
    image: postgres:14
    container_name: photo-animation-db
    restart: always
    environment:
      POSTGRES_USER: yesi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: photoanimationdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yesi"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photo-animation-backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DATABASE_URL: "postgresql://yesi:secret@db:5432/photoanimationdb"
volumes:
  postgres_data:
